let route = [{
    title: '首页',
    route: '/',
    page: '/Home/index.html'
}, {
    title: '首页',
    route: '/Home',
    page: '/Home/index.html'
}, {
    title: '专业审核',
    route: '/Identity/Assess',
    page: '/Identity/Assess.html'
}, {
    title: '身份认证',
    route: '/Identity/IdentityEntrance',
    page: '/Identity/IdentityEntrance.html'
}, {
    title: '完善企业资料',
    route: '/Identity/IdentityInfo',
    page: '/Identity/IdentityInfo.html'
}, {
    title: '企业认证成功',
    route: '/Identity/IdientitySuccess',
    page: '/Identity/IdientitySuccess.html'
}, {
    title: '完善个人资料',
    route: '/Identity/PersonalCertificate',
    page: '/Identity/PersonalCertificate.html'
}, {
    title: '岗位认证',
    route: '/Identity/PostTheCertification',
    page: '/Identity/PostTheCertification.html'
}, {
    title: '登录',
    route: '/Login',
    page: '/Login/Login.html'
}, {
    title: '项目报名',
    route: '/LookingFor/Apply',
    page: '/LookingFor/Apply.html'
}, {
    title: '项目详情',
    route: '/LookingFor/LookDetails',
    page: '/LookingFor/LookDetails.html'
}, {
    title: '寻找项目首页',
    route: '/LookingFor/LookingFor',
    page: '/LookingFor/LookingFor.html'
}, {
    title: '寻找项目列表',
    route: '/LookingFor/LookingForList',
    page: '/LookingFor/LookingForList.html'
}, {
    title: '我参与的项目',
    route: '/LookingFor/MyProject',
    page: '/LookingFor/MyProject.html'
}, {
    title: '我的任务',
    route: '/LookingFor/MyTask',
    page: '/LookingFor/MyTask.html'
}, {
    title: '账号绑定',
    route: '/Member/AccountBinding',
    page: '/Member/AccountBinding.html'
}, {
    title: '银行卡绑定',
    route: '/Member/BindingBankCard',
    page: '/Member/BindingBankCard.html'
}, {
    title: '绑定微信',
    route: '/Member/BindingWeChat',
    page: '/Member/BindingWeChat.html'
}, {
    title: '修改邮箱',
    route: '/Member/EditEmail',
    page: '/Member/EditEmail.html'
}, {
    title: '修改密码',
    route: '/Member/EditPaddWord',
    page: '/Member/EditPaddWord.html'
}, {
    title: '修改手机号',
    route: '/Member/EditPhone',
    page: '/Member/EditPhone.html'
}, {
    title: '基本资料',
    route: '/Member/Info',
    page: '/Member/Info.html'
}, {
    title: '新消息设置',
    route: '/Member/Message',
    page: '/Member/Message.html'
}, {
    title: '项目沟通',
    route: '/Member/ProjectInterflow',
    page: '/Member/ProjectInterflow.html'
}, {
    title: '安全设置',
    route: '/Member/Security',
    page: '/Member/Security.html'
}, {
    title: '公告栏',
    route: '/Notice/NoticeDetails',
    page: '/Notice/NoticeDetails.html'
}, {
    title: '平台审核',
    route: '/PublishProject/Audit',
    page: '/PublishProject/Audit.html'
}, {
    title: '消息反馈',
    route: '/PublishProject/Feedback',
    page: '/PublishProject/Feedback.html'
}, {
    title: '审核历史',
    route: '/PublishProject/History',
    page: '/PublishProject/History.html'
}, {
    title: '图库',
    route: '/PublishProject/MapDepot',
    page: '/PublishProject/MapDepot.html'
}, {
    title: '缴纳费用',
    route: '/PublishProject/PayTheFees',
    page: '/PublishProject/PayTheFees.html'
}, {
    title: '项目沟通',
    route: '/PublishProject/projectLinkUp',
    page: '/PublishProject/projectLinkUp.html'
}, {
    title: '发布首页',
    route: '/PublishProject/Publish',
    page: '/PublishProject/Publish.html'
}, {
    title: '发布项目',
    route: '/PublishProject/PublishProject',
    page: '/PublishProject/PublishProject.html'
}, {
    title: '招募人员',
    route: '/PublishProject/Recruit',
    page: '/PublishProject/Recruit.html'
}, {
    title: '已发布项目',
    route: '/PublishProject/Released',
    page: '/PublishProject/Released.html'
}, {
    title: '缴纳费用',
    route: '/PublishProject/ReleaseSuccess',
    page: '/PublishProject/ReleaseSuccess.html'
}, {
    title: '填写项目信息',
    route: '/PublishProject/SubmitInfo',
    page: '/PublishProject/SubmitInfo.html'
}, {
    title: '样图详情',
    route: '/PublishProject/SubmitInfoImg',
    page: '/PublishProject/SubmitInfoImg.html'
}, {
    title: '上传资料',
    route: '/PublishProject/SubmitInfoUp',
    page: '/PublishProject/SubmitInfoUp.html'
}, {
    title: '任务拆分',
    route: '/PublishProject/TaskSplit',
    page: '/PublishProject/TaskSplit.html'
}, {
    title: '人才库',
    route: '/TalentPool/TalentPoolList',
    page: '/TalentPool/TalentPoolList.html'
}, {
    title: '首页',
    route: '/Web/Home',
    page: '/Web/Home.html'
}, {
    title: '已完成项目',
    route: '/Web/OverProject',
    page: '/Web/OverProject.html'
}, {
    title: '进行中项目',
    route: '/Web/StartProject',
    page: '/Web/StartProject.html'
}, {
    title: '人才列表',
    route: '/Web/Talents',
    page: '/Web/Talents.html'
}, {
    title: '收藏项目',
    route: '/Collect',
    page: '/Collect/index.html'
}, {
    title: '关注人才',
    route: '/FocusTalent',
    page: '/FocusTalent/index.html'
}, {
    title: '审核人',
    route: '/Auditor',
    page: '/Auditor/Auditor.html'
}, {
    title: '项目绑定',
    route: '/ProjectBinding',
    page: '/ProjectBinding/ProjectBinding.html'
}, {
    title: '我的积分',
    route: '/Integral',
    page: '/Integral/Integral.html'
}, {
    title: '收支明细',
    route: '/Income',
    page: '/Income/Income.html'
}];
module.exports = route;